[build]
  base = "apps/web"
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-frozen-lockfile"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_TIKTOK_CLIENT_KEY"

[[plugins]]
  package = "@netlify/plugin-nextjs"
